---
title: "Segmentation and Profiling Project"
author: "June Lemieux"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(rpart)
library(rpart.plot)
library(tidyverse)
library(ggplot2)
library(lubridate)

# import data - this data set is the result from DueDiligenceStudy.rmd
df <- read_csv(".\\Customer_Dataset_Data_Revised.csv")
set.seed(123)

```


```{r}
# Unsupervised Segmentation Technique
# do the stuff
set.seed(123)
NUM_CLUSTERS <- 5
points <- df %>% select(c("TotTelecomLastMonth","HHIncome","OfferingCount"))
#points <- scale(points)
kclust <- kmeans(points, centers = NUM_CLUSTERS, nstart = 25)

# Add segments to original dataset
df$kmeans_segment <- as.factor(kclust$cluster)

# Segment Profiles
df %>% select(c("kmeans_segment","TotTelecomLastMonth","HHIncome","OfferingCount")) %>% add_count(kmeans_segment) %>%
  group_by(kmeans_segment,n) %>% 
  summarise_all("mean") 
```
## Choosing a good number of clusters
We may want to investigate how the total within cluster variation changes as we increase the number of segments.
```{r}
ks <- 1:10
tot_within_ss <- sapply(ks, function(k) {
    set.seed(123)
    cl <- kmeans(points, k)
    cl$tot.withinss
})
plot(ks, tot_within_ss, type = "b")
```

## Visualization for unsupervised
Here's visualization of the segments featuring two real-valued variables.
```{r}
g <- ggplot(df)+geom_point(aes(x=HHIncome,y=TotTelecomLastMonth,colour=kmeans_segment))+scale_x_continuous(trans='log10')
print(g)
```


## Rules-based to create groups 
```{r}
#First 
g <- ggplot(data=df) + geom_histogram(aes(x=TotTelecomLastMonth))
print(g)

g <- ggplot(data=df) + geom_histogram(aes(x=OfferingCount))
print(g)

g <- ggplot(data=df) + geom_histogram(aes(x=HHIncome))+scale_x_continuous(trans='log10')
print(g)

```
```{r}
df$TotTelecomRule <- cut(df$TotTelecomLastMonth, breaks=c(-1,75,600), labels=c("Low","High"))

df$OfferRule <- cut(df$OfferingCount, breaks=c(-1,7,20), labels=c("Low","High"))

df$HHIncRule <- cut(df$HHIncome, breaks=c(-1,90001,1100000), labels=c("Low","High"))

df <- df %>% rowwise %>%
  mutate(RuleDistro = sum(c_across(ends_with('Rule')) == "High")) %>%
  ungroup                    

## Combined rules to create segments
df <- df %>% mutate(segment = case_when(
	RuleDistro == 3 ~ 1,
	RuleDistro == 2 ~ 2,
	RuleDistro == 1 ~ 3,
	TRUE ~ 4
	))
	
## Segment profiles

df %>% add_count(segment) %>%
	group_by(segment,n) %>%
	summarise_all("mean")

df %>% select(c("segment","TotTelecomLastMonth","HHIncome","OfferingCount")) %>% add_count(segment) %>%
  group_by(segment,n) %>% 
  summarise_all("mean")
	
## Visualization

g <- ggplot(df) + geom_point(aes(x=HHIncome, y=TotTelecomLastMonth,color=as.factor(segment)))+scale_x_continuous(trans='log10') 
print(g)	
```

```{r}
df %>% write_csv(".\\output_of_segmentation.csv")
```